#!/bin/bash
cd $(dirname "$0")

if [ "$1" == "start" ]
then
	n=${2:-5}
	((x=n-1))

	if [ $x -lt 0 ]
	then
		x=0;
	fi
	
	./$1.exe $x
	echo "NginX Server started!"
elif [ "$1" == "server" ]
then
	if [ "$2" == "--prod" ]
	then
		cp -f ./php/opcache/php-prod.ini ./php/php.ini
		echo "Server in production mode"
	else
		cp -f ./php/opcache/php-dev.ini ./php/php.ini
		echo "Server in development mode"
	fi
elif [ "$1" == "--create" ] || [ "$1" == "-c" ]
then
	root=${2//\\//}
	sblock="
	server {
	  listen ${4:-80};
	  listen [::]:${4:-80};

	  index index.php index.html;
	  root ${root:-/html};

	  server_name ${5:-localhost};

	  location / {
		autoindex on;
		autoindex_exact_size off;
		autoindex_format html;
		autoindex_localtime on;
		try_files \$uri \$uri/ /index.php?\$args;
	  }

	  client_max_body_size 128M;

	  location ~* \\.php\$ {
		include fastcgi.conf;
		fastcgi_split_path_info ^(.+\\.php)(/.+)\$;
		fastcgi_pass backend;
		fastcgi_index index.php;
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
		fastcgi_param PATH_INFO \$fastcgi_path_info;
		fastcgi_read_timeout 300s;
	  }
	  listen $((${4:-442}+1)) ssl;
	  listen [::]:$((${4:-442}+1)) ssl;
	  
	  ssl_certificate ../ssl/server.crt;
	  ssl_certificate_key ../ssl/server.key;
	  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	}";
	
	echo $sblock > ./sites-enabled/${3:-default}@${5:-localhost}[${4:-80}].conf
	echo "NginX Server ${3:-default} -> ${5:-localhost}:${4:-80} created!"
elif [ "$1" == "--delete" ] || [ "$1" == "-d" ]
then
	if [ "$2" == "--all" ]
	then
		rm ./sites-enabled/*.conf
		echo "NginX Server blocks deleted!"
	else
		file="./sites-enabled/${2}*.conf"
		if [ -f $file ]
		then
			rm $file
			echo "NginX Server $2 deleted!"
		else
			echo "Server Block not Found!"
		fi
	fi
elif [ "$1" == "stop" ]
then
	./$1.exe
	echo "NginX Server stopped!"
elif [ "$1" == "--list" ] || [ "$1" == "-l" ]
then
	ls ./sites-enabled/ | sed -e 's/\.conf$//'
else
	echo "Usage:";
	echo " - nginx [--create|-c] [root_directory|default: '/html'] [block_name|default: default] [port|default: 80] [server_name|default: localhost]";
	echo " - nginx server [--prod|default: empty]";
	echo " - nginx [--delete|-d] [server_name|--all for delete all]";
	echo " - nginx start [max_upstream_server|default: 5]";
	echo " - nginx stop";
	echo " - nginx [--list|-l]";
	echo "";
	echo "Important: Make sure to execute \"nginx stop\" before run create or destroy command!";
fi
