#!/bin/bash
cd $(dirname "$0")

if [ "$1" == "start" ]
then
	n=${4:-5}
	((x=n-1))

	if [ $x -lt 0 ]
	then
		x=0;
	fi
	sblock="server {
	  listen ${3:-80} default_server;
	  listen [::]:${3:-80} default_server;

	  index index.php index.html;
	  root ${2:-/html};

	  server_name ${5:-localhost};

	  location / {
		try_files \$uri \$uri/ /index.php?\$args;
	  }

	  client_max_body_size 128M;

	  location ~* \\.php\$ {
		try_files \$uri =404;
		fastcgi_split_path_info ^(.+\\.php)(/.+)\$;
		fastcgi_pass backend;
		fastcgi_index index.php;
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
		fastcgi_param PATH_INFO \$fastcgi_path_info;
		fastcgi_read_timeout 300;
	  }
	}";
	
	
	f='upstream backend{';
	for i in $(seq 0 $x);
	do
		p="900${i}";
		if [ $i -gt 9 ]
		then
			p="90${i}";
		fi
		f="${f} server 127.0.0.1:${p} weight=1 fail_timeout=3s;";
	done
	f="${f} }"
	
	echo $sblock > ./sites-enabled/default.conf
	echo $f > ./conf/upstream.conf
	./$1.bat $x
	echo "NginX Server started!"
elif [ "$1" == "stop" ]
then
	./$1.bat
	echo "NginX Server stopped!"
else
	echo "Usage: [start|stop] [root_directory|default: '/html'|<string>] [port|default: 80|<number>] [max_upstream_server|default: 5|<number>] [server_name|default: localhost|<string>]";
fi
